---
deployment:
  tasks:
    - export DEPLOYPATH=/home/workstudy/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp activity.php $DEPLOYPATH
    - /bin/cp addstudent.php $DEPLOYPATH
    - /bin/cp admin-back.php $DEPLOYPATH
    - /bin/cp attend.php $DEPLOYPATH
    - /bin/cp attendance.php $DEPLOYPATH
    - /bin/cp back.php $DEPLOYPATH
    - /bin/cp delete.php $DEPLOYPATH
    - /bin/cp edit.php $DEPLOYPATH
    - /bin/cp export.php $DEPLOYPATH
    - /bin/cp home.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp register.php $DEPLOYPATH
    - /bin/cp reset-password.php $DEPLOYPATH
    - /bin/cp settings.php $DEPLOYPATH
    - /bin/cp studentlogin.php $DEPLOYPATH
